---
title: "Biostat M280 Homework 1"
author: "Haowen Xu  <haowenxu930622@outlook.com>"
output: html_document
---

## Q2. Linux Shell Commands

1. Display the first few lines of `NYCHVS_1991.csv`.

**Solution:**
```{bash eval=FALSE}
head /home/m280data/NYCHVS/NYCHVS_1993.csv
```

2. Display number of lines in each `csv` file.

**Solution:**

```{bash}
wc -l /home/m280data/NYCHVS/*.csv
```

14901 /home/m280data/NYCHVS/NYCHVS_1991.csv
15802 /home/m280data/NYCHVS/NYCHVS_1993.csv
15754 /home/m280data/NYCHVS/NYCHVS_1996.csv
15419 /home/m280data/NYCHVS/NYCHVS_1999.csv
15896 /home/m280data/NYCHVS/NYCHVS_2002.csv
15549 /home/m280data/NYCHVS/NYCHVS_2005.csv
17957 /home/m280data/NYCHVS/NYCHVS_2008.csv
16360 /home/m280data/NYCHVS/NYCHVS_2011.csv
15344 /home/m280data/NYCHVS/NYCHVS_2014.csv
13268 /home/m280data/NYCHVS/NYCHVS_2017.csv
156250 total

3. Display the 3 files that have the least number of lines

**Solution:**

```{bash}
wc -l /home/m280data/NYCHVS/*.csv | sort | head -3
```


4. What's the output of following bash script?

**Solution:**

This bash script output all the .csv files in the path '/home/m280data/NYCHVS/'.

/home/m280data/NYCHVS/NYCHVS_1991.csv

/home/m280data/NYCHVS/NYCHVS_1993.csv

/home/m280data/NYCHVS/NYCHVS_1996.csv

/home/m280data/NYCHVS/NYCHVS_1999.csv

/home/m280data/NYCHVS/NYCHVS_2002.csv

/home/m280data/NYCHVS/NYCHVS_2005.csv

/home/m280data/NYCHVS/NYCHVS_2008.csv

/home/m280data/NYCHVS/NYCHVS_2011.csv

/home/m280data/NYCHVS/NYCHVS_2014.csv

/home/m280data/NYCHVS/NYCHVS_2017.csv


5. What unique values does the second variable `borough` take in
`NYCHVS_1991.csv`? Tabulate how many times each value appears.

**Solution:**

First find all the second variable with comma seperator, then sort the file and 
find unique number of each value, then sort again. Since the count I get has 
two values from the header, find the first 5 to exclude this value.

```{bash}
awk -F ',' '{ print $2 }' /home/m280data/NYCHVS/NYCHVS_1991.csv | sort | 
uniq -c | sort -nr | head -5
```
| $Value$ | $Count$ |
|-----|----------|
| 1 | 2271 |
| 2 | 4412 |
| 3 | 3780 |
| 4 | 3702 |
| 5 | 734  |


## Q3. More fun with shell

1. **Solution:**

grep -o output the specified keyword and display one at a line, the use wc -l
to count the number of lines in the output which equal to the number of count
of the specified word.

```{bash}
for name in "Elizabeth" "Jane" "Lydia" "Darcy"
  do
    grep -o $name /home/haowenxu930622/pride_and_prejudice.txt | wc -l
  done
```

| $Name$ | $Count$ |
|-----|----------|
| Elizabeth | 635 |
| Jane | 295 |
| Lydia | 170 |
| Darcy | 417 |

2. **Solution:**

The first command remove everything in test1.txt file and write 'hello, world'
into the same file. The second command append 'hello, world' into the last line
of test2.txt file.

3. **Solution:**

The output print the last 5 lines of the first 20 lines in the
'pride_and_prejudice.txt' file. "$1", "$2", and "$3" are corresponding to 
"pride_and_prejudice.txt", "20" and "5" in our argument.  The first line tells
us that the script should be executed using 'sh' shell.


## Q4. R Batch Run

1.**Solution:**

Test run:
```{bash}
Rscript runSim.R n=10 rep=5 seed=1 dist=\"gaussian\"
Rscript runSim.R n=10 rep=5 seed=1 dist=\"t1\"
Rscript runSim.R n=10 rep=5 seed=1 dist=\"t5\"
```

Here is my runSim.R code:
```{R eval=FALSE}
## parsing command arguments
for (arg in commandArgs(TRUE)) {
  eval(parse(text=arg))
}

## check if a given integer is prime
isPrime = function(n) {
  if (n <= 3) {
    return (TRUE)
  }
  if (any((n %% 2:floor(sqrt(n))) == 0)) {
    return (FALSE)
  }
  return (TRUE)
}

## estimate mean only using observation with prime indices
estMeanPrimes = function (x) {
  n = length(x)
  ind = sapply(1:n, isPrime)
  return (mean(x[ind]))
}

#set seed
set.seed(seed)
#simulation function
sim = function (n, dist){
  if (dist == "gaussian") {
    x = rnorm(n)
  }else if (dist == "t1"){ 
    x = rt(n, df = 1)
  }else if (dist == "t5"){
    x = rt(n, df = 5)
  }
  return (x)
}
#creat empty vector to store mean value for each simulation
prime_mean <- vector(length = rep)
classic_mean <- vector(length = rep)
#simulating rep times and store it's mean
for(i in 1 : rep){
  prime_mean[i] <- estMeanPrimes(sim(n, dist))
  classic_mean[i] <- mean(sim(n, dist))
}
#calculate MSE, true mean is 0 for standard normal and t distribution
mse = function (x, y, repetition){
  prime_mse = sum(x ^ 2) / repetition
  classic_mse = sum(y ^ 2) / repetition
  return(paste(prime_mse, classic_mse))
}
#call mse function with simulated means created previously
mse(prime_mean, classic_mean, rep)
```
2.**Solution:**

Here is my autoSim.R code:
```{R eval=FALSE}
# autoSim.R
nVals <- seq(100, 500, by=100)
distTypes <- c("gaussian", "t1", "t5")
rep <- 50
seed <- 280
for (n in nVals) {
  for (m in distTypes){
  oFile <- paste("n", n, "dist_", m, ".txt", sep="")
  sysCall <- paste("nohup Rscript runSim.R n=", n, " dist=", shQuote(shQuote(m)),
                   " rep=", rep, " seed=", seed, " > ", oFile, sep="")
  system(sysCall)
  print(paste("sysCall=", sysCall, sep=""))
  }
}
```

3.**Solution:**

Test Run:
```{bash}
Rscript q4_summary.R
```

Here is my q4_summary.R code
```{R}
nVals <- seq(100, 500, by=100)
distTypes <- c("gaussian", "t5", "t1")

#Create a matrix with required label
simulation <- matrix(NA, nrow= 10, ncol = 5)
colnames(simulation) <- c("n", "Method", "Gaussian", "t5", "t1")
rownames(simulation) <- c("1", "2", "3", "4", "5", "6",
                          "7", "8", "9", "10")

#set counter for matrix
i = 1

#
for (n in nVals) {
  simulation[i, 1] <- n
  simulation[i + 1, 1] <- n
  simulation[i, 2] <- "PrimeAvg"
  simulation[i + 1, 2] <- "SampAvg"
  j = 3
  for (m in distTypes){
    #Generate path for each file with different name
    file <- paste("n", n, "dist_", m, ".txt",sep="")
    path <- paste("/home/haowenxu930622/biostat-m280-2019-winter/hw1/", file, sep="")
    
    #Read in data
    x <- read.table(path)
    
    #Input data from file
    simulation[i, j] <- as.character(x[2])
    simulation[i + 1, j] <- as.character(x[3])
    j = j + 1
  }
  i <- i + 2
}

simulation

```

