---
title: "Biostat M280 Homework 3"
author: "Haowen Xu  <haowenxu930622@outlook.com>"
output: html_document
---

## Q1. LA City Employee Payroll

**1.Solution:**

Transform data and save it as RDS file:
```{R, eval = FALSE}
library("tidyverse")
pay <- read_csv('/home/m280data/la_payroll/City_Employee_Payroll.csv')
names(pay) <- str_replace_all(names(pay), " ", "_")
pay <- mutate(pay, other_pay = Total_Payments - Base_Pay - Overtime_Pay) %>%         select(Year, Department_Title, Total_Payments, Base_Pay, Overtime_Pay,
                                                                                            other_pay, Row_ID)
saveRDS(pay, file = "payroll.rds")
```

Here is my Shiny code:
```{R, eval=FALSE}
library("tidyverse")
library("shiny")
library("reshape2")

#read in data
pay <- readRDS("/data/payroll.rds")

# Define UI ----
ui <- fluidPage(
  titlePanel("LA City Employee Payroll"),
  
  sidebarLayout(
    sidebarPanel(helpText("LA city employee payroll information from 2013 to
                          2018."),
                 selectInput("question", 
                             label = "Choose a question to display:",
                             choices = c("Total payroll(Q2)",
                                         "Who earned most?(Q3)",
                             "Which department earned most?(Q4)",
                             "Which department cost most?(Q5)"),
                             selected = "Total payroll"),
                 numericInput(inputId = "size",
                              label = "Number of observations to view(Q3~5):",
                              value = 5),
                 selectInput("year",
                             label = "Choose year of interest(Q2~5):",
                             choices = c("2013", "2014", "2015", "2016",
                                         "2017", "2018"),
                             selected = "2017"),
                 selectInput("method",
                             label = "Method(Q4):",
                             choices = c("Median", "Mean"),
                             selected = "Median")),
    mainPanel(plotOutput("myplot"))
  )
  
)

# Define server logic ----
server <- function(input, output) {
  
  output$myplot <- renderPlot({
    
    if(input$question == "Total payroll(Q2)"){
      data <- summarize(group_by(pay, Year), base = sum(Base_Pay,
                                                        na.rm = TRUE),
                        over = sum(Overtime_Pay, na.rm = TRUE),
                        other = sum(other_pay, na.rm = TRUE))
      data <- melt(data, id.var = "Year")
      ggplot(data, aes(x = reorder(as.factor(Year), -value), y = value,
                       fill = variable)) +
        geom_bar(stat="identity") +
        ggtitle("Total payroll by LA city") +
        xlab("Year") + ylab("Total Payment") + 
        scale_y_continuous()
    }else if(input$question == "Who earned most?(Q3)"){
      data <- arrange(pay, desc(Total_Payments)) %>%
        filter(Year == as.character(input$year)) %>%
        head(input$size)%>%
        mutate(rank = dense_rank(desc(Total_Payments))) %>%
        select(Base_Pay, Overtime_Pay, other_pay, rank) 
      data <- melt(data, id.var = "rank")
      ggplot(data, aes(x = as.factor(rank), y = value, fill = variable)) +
        geom_bar(stat="identity") +
        ggtitle("Who earned most?") +
        xlab("ID") + ylab("Total Payment") + scale_y_continuous()
    }else if(input$question == "Which department earned most?(Q4)"){
      data <- filter(pay, Year == as.character(input$year)) %>%
        group_by(Department_Title) %>%
        summarize(mean_tot = mean(Total_Payments, na.rm = TRUE),
                  mean_base = mean(Base_Pay, na.rm = TRUE),
                  mean_over = mean(Overtime_Pay, na.rm = TRUE),
                  mean_other = mean(other_pay, na.rm = TRUE),
                  median_base = median(Base_Pay, na.rm = TRUE),
                  median_over = median(Overtime_Pay, na.rm = TRUE),
                  median_other = median(other_pay, na.rm = TRUE),
                  median_tot = median(Total_Payments, na.rm = TRUE))
      if(input$method == "Median"){
        data <- arrange(data, desc(median_tot)) %>%
          head(input$size) %>%
          select(Department_Title, median_base, median_over, median_other)
        data <- melt(data, id.var = "Department_Title")
        ggplot(data, aes(x = reorder(as.factor(Department_Title), -value),
                         y = value,
                         fill = variable)) +
          geom_bar(stat="identity") +
          ggtitle("Which department earned most by median?") +
          xlab("Department") + ylab("Total Earned") + 
          scale_y_continuous() +
          theme(axis.text.x = element_text(angle = 90, hjust = 1))
      }else if(input$method == "Mean"){
        data <- arrange(data, desc(mean_tot)) %>%
          head(input$size) %>%
          select(Department_Title, mean_base, mean_over, mean_other)
        data <- melt(data, id.var = "Department_Title")
        ggplot(data, aes(x = reorder(as.factor(Department_Title), -value),
                         y = value,
                         fill = variable)) +
          geom_bar(stat="identity") +
          ggtitle("Which department earned most by mean?") +
          xlab("Department") + ylab("Total Earned") + 
          scale_y_continuous() +
          theme(axis.text.x = element_text(angle = 90, hjust = 1))
      }
    }else if(input$question == "Which department cost most?(Q5)"){
      data <- filter(pay, Year == as.character(input$year)) %>%
        group_by(Department_Title) %>%
        summarize(tot = sum(Total_Payments), base = sum(Base_Pay),
                  over = sum(Overtime_Pay), other = sum(other_pay)) %>%
        arrange(desc(tot)) %>%
        head(input$size) %>%
        select(Department_Title, base, over, other)
      data <- melt(data, id.var = "Department_Title")
      ggplot(data, aes(x = reorder(as.factor(Department_Title), -value),
                       y = value,
                       fill = variable)) +
        geom_bar(stat="identity") +
        ggtitle("Which department cost the most?") +
        xlab("Department") + ylab("Total cost") + 
        scale_y_continuous() +
        theme(axis.text.x = element_text(angle = 90, hjust = 1))
    }
  })
}

# Run the app ----
shinyApp(ui = ui, server = server)
```

**2.Solution:**

Total payroll each year:
```{R}
library("tidyverse")
pay <- readRDS("shinyapps/data/payroll.rds")
data <- summarize(group_by(pay, Year), base = sum(Base_Pay),
                        over = sum(Overtime_Pay, na.rm = TRUE),
                        other = sum(other_pay, na.rm = TRUE))
data
```

**3.Solution:**

Example: Top 10 payroll in 2015.
```{R}
data <- arrange(pay, desc(Total_Payments)) %>%
        filter(Year == as.character(2015)) %>%
        head(10)%>%
        mutate(rank = dense_rank(desc(Total_Payments))) %>%
        select(Row_ID, Total_Payments, Base_Pay, Overtime_Pay, other_pay, rank)
data
```

**4.Solution:**

Example: Top 10 department earned most in 2014 using median.
```{R}
data <- filter(pay, Year == as.character(2014)) %>%
  group_by(Department_Title) %>%
  summarize(median_base = median(Base_Pay, na.rm = TRUE),
            median_over = median(Overtime_Pay, na.rm = TRUE),
            median_other = median(other_pay, na.rm = TRUE),
            median_tot = median(Total_Payments, na.rm = TRUE)) %>%
  arrange(desc(median_tot)) %>%
  head(10) %>%
  select(Department_Title, median_tot, median_base, median_over, median_other)
data
```

**5.Solution:**

Example: Top 6 department cost the most in 2018.
```{R}
data <- filter(pay, Year == as.character(2018)) %>%
  group_by(Department_Title) %>%
  summarize(tot = sum(Total_Payments), base = sum(Base_Pay),
            over = sum(Overtime_Pay), other = sum(other_pay)) %>%
  arrange(desc(tot)) %>%
  head(6) %>%
  select(Department_Title, tot, base, over, other)
data
```

**6.Solution:**

Example: Top 5 department with highest total overtime pay in 2018.
```{R}
data <- filter(pay, Year == as.character(2018)) %>%
  group_by(Department_Title) %>%
  summarize(tot = sum(Total_Payments), base = sum(Base_Pay),
            over = sum(Overtime_Pay), other = sum(other_pay)) %>%
  arrange(desc(base)) %>%
  head(5) %>%
  select(Department_Title, base)
data
ggplot(data, aes(x = reorder(as.factor(Department_Title), -base), y = base)) +
  geom_bar(stat="identity")
```

**7.Solution:**

Here is the link to my Shiny app:
https://haowenxu.shinyapps.io/shinyapps/



## Q2. LA City Parking War

Connect to the data base:
```{R}
library("DBI")
library("RSQLite")
library("tidyverse")
library("lubridate")
parking <- dbConnect(RSQLite::SQLite(),
              dbname = "/home/m280data/la_parking/LA_Parking_Citations.sqlite")
dbListTables(parking)
parking_sql <- dplyr::tbl(parking, "latix")
parking_sql %>% print(width = Inf)
```

**1.Solution:**

Total number of tickects: 
  
  7656418
  
Number of tickets each year:
  
  2015	  | 1068245			
  2016	  | 2177956			
  2017	  | 2235243			
  2018	  | 1976451			
  2019	  | 124458	

Here is my R code:
```{R}
#Simplify data
parking_data <- select(parking_sql, Ticket_number, Issue_DateTime, Issue_Year,
                       Issue_Month, Issue_Day, Issue_Hour, Issue_Wday,
                       Make, Color, Fine_amount, Violation_code,
                       Violation_Description)
#Total number of tickets
summarize(parking_data, n = n()) %>% collect()
#Tickects by year
ticket <- filter(parking_data, Issue_Year > 0)%>%
  group_by(Issue_Year) %>% 
  summarize(n = n()) %>%
  collect()
ticket
#Plot
ggplot(ticket, aes(x = as.factor(Issue_Year), y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Number of tickets collected by year.") +
  xlab("Year") + ylab("Number of tickets")
```

**2.Solution:**

You are most likely to get a ticket at :

Hour       | 12 p.m.

Week day   | Wednesday

Month day  | 13

Month      | August

You are least likely to get a ticket at :

Hour       | 5 a.m.

Week day   | Monday

Month day  | 31

Month      | Feburary

Here is my R code:

```{R}
#Distribution of number of ticket by month
month <- filter(parking_data, Issue_Month > 0) %>%
  group_by(Issue_Month) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) %>%
  collect()
head(month, 1)
tail(month, 1)
ggplot(month, aes(x = as.factor(Issue_Month), y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Number of tickets collected by month") +
  xlab("Month") + ylab("Number of tickets")

#Distribution of number of ticket by day
day <- filter(parking_data, Issue_Day > 0) %>%
  group_by(Issue_Day) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) %>%
  collect()
head(day, 1)
tail(day, 1)
ggplot(day, aes(x = as.factor(Issue_Day), y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Number of tickets collected by month day") +
  xlab("Month day") + ylab("Number of tickets")

#Distribution of number of ticket by week day
wday <- filter(parking_data, Issue_Wday > 0) %>%
  group_by(Issue_Wday) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) %>%
  collect()
head(wday, 1)
tail(wday, 1)
ggplot(wday, aes(x = as.factor(Issue_Wday), y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Number of tickets collected by week day") +
  xlab("Week day") + ylab("Number of tickets")

#Distribution of number of ticket by Hour
hour <- filter(parking_data, Issue_Hour > 0) %>%
  group_by(Issue_Hour) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) %>%
  collect()
head(hour, 1)
tail(hour, 1)
ggplot(hour, aes(x = as.factor(Issue_Hour), y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Number of tickets collected by hour") +
  xlab("Hour") + ylab("Number of tickets")

```

**3.Solution:**

The car make that receives most citations is: Toyota

Here is my R code:
```{R}
make <- filter(parking_data, is.na(Make) == FALSE) %>%
  group_by(Make) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) %>%
  head(10) %>%
  collect()
ggplot(make, aes(x = reorder(as.factor(Make), -n), y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Top 10 make received most citation in LA") +
  xlab("Make") + ylab("Number of tickets")
```

**4.Solution:**

Total number of car colors: 103

The color or cars receives most tickets: Black

Here is my R code:
```{R}
color <- filter(parking_data, is.na(Color) == FALSE) %>%
  group_by(Color) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) %>%
  collect()
nrow(color)
head(color, 1)
color <- head(color, 10)
ggplot(color, aes(x = reorder(as.factor(Color), -n), y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Top 10 color of car that received most citation in LA") +
    xlab("Color") + ylab("Number of tickets")
```

**5.Solution:**

The most common ticket type is: NO PARK/STREET CLEAN

Here is my R code:
```{R}
type <- filter(parking_data, is.na(Violation_Description) == FALSE) %>%
  group_by(Violation_Description) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) %>%
  head(10) %>%
  collect()
print(type, n = 10)
```

**6.Solution:**

Total amount of money collected on parking in 2016, 2017, 2018 are:

Year  Amount

2016	75026770			

2017	76876603			

2018	70060345

Here is my R code:
```{R}
money <- filter(parking_data, is.na(Fine_amount) == FALSE, 
                is.na(Issue_Year) == FALSE) %>%
  group_by(Issue_Year, Violation_Description) %>%
  summarize(amount = sum(Fine_amount)) %>%
  arrange(Issue_Year) %>%
  collect()
#Can not apply grepl() when using value from database
money <- filter(money, grepl("PARK", Violation_Description)) %>%
  group_by(Issue_Year) %>%
  summarize(amount = sum(amount)) %>%
  arrange(Issue_Year)
print(money)
```

**7.Solution:**

I have never been ticketed in LA county.

Close connection to the database:
```{R}
dbDisconnect(parking)
```
